//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationUsingFetchXml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_MessageBoxText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_MessageBoxText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataMigrationUsingFetchXml.Localization-MessageBoxText", typeof(Localization_MessageBoxText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to the source instance..
        /// </summary>
        internal static string ConnectToTheSourceInstance {
            get {
                return ResourceManager.GetString("ConnectToTheSourceInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Migration Completed..
        /// </summary>
        internal static string DataMigrationCompleted {
            get {
                return ResourceManager.GetString("DataMigrationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching criteria are not available for the action CREATE..
        /// </summary>
        internal static string DisableMatchingCriteriaForActionCreate {
            get {
                return ResourceManager.GetString("DisableMatchingCriteriaForActionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This FetchXML already exists. A duplicate FetchXML cannot be added..
        /// </summary>
        internal static string DuplicateFetchXml {
            get {
                return ResourceManager.GetString("DuplicateFetchXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all the fields before adding a new row..
        /// </summary>
        internal static string FillAllFieldsBeforeAdding {
            get {
                return ResourceManager.GetString("FillAllFieldsBeforeAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching Criteria will be cleared as there are missing fields in FetchXml..
        /// </summary>
        internal static string MatchingCriteriaWillBeCleared {
            get {
                return ResourceManager.GetString("MatchingCriteriaWillBeCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration is Stopped..
        /// </summary>
        internal static string MigrationIsStopped {
            get {
                return ResourceManager.GetString("MigrationIsStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one row from FetchXML table for data transfer..
        /// </summary>
        internal static string SelectRowForTransfer {
            get {
                return ResourceManager.GetString("SelectRowForTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Target Instance..
        /// </summary>
        internal static string SelectTargetInstance {
            get {
                return ResourceManager.GetString("SelectTargetInstance", resourceCulture);
            }
        }
    }
}
